@extends('employee.layout.app')

@section('content')
    <div class="">
        <div class="section-card">
            <h2 class="section-title">Attendance Management</h2>
            <div class="attendance-actions" style="margin-bottom: 20px;">
                {{-- <button class="btn btn-success" id="markAttendanceBtn">
                    <i class="fas fa-fingerprint"></i> Mark Attendance
                </button> --}}
                <button class="btn btn-warning" id="requestRegularizationBtn">
                    <i class="fas fa-clock"></i> Request Regularization
                </button>
                <button class="btn btn-info" id="attendanceReportBtn">
                    <i class="fas fa-chart-bar"></i> Generate Report
                </button>
            </div>

            <div class="calendar" style="margin-bottom: 30px;">
                <div class="calendar-header">
                    <button class="btn btn-secondary" id="prevMonthBtn">
                        <i class="fas fa-chevron-left"></i>
                    </button>
                    <h3 id="currentMonth">June 2023</h3>
                    <button class="btn btn-secondary" id="nextMonthBtn">
                        <i class="fas fa-chevron-right"></i>
                    </button>
                </div>
                <div class="calendar-grid" id="attendanceCalendar">
                    <!-- Calendar will be generated by JavaScript -->
                </div>
            </div>

            <h3 style="margin-bottom: 20px;">Attendance History</h3>
            <div style="margin-bottom: 20px;">
                <select class="form-control" id="attendanceMonthFilter" style="width: 200px; display: inline-block;">
                    <option value="0">All Months</option>
                    <option value="1">January</option>
                    <option value="2">February</option>
                    <option value="3">March</option>
                    <option value="4">April</option>
                    <option value="5">May</option>
                    <option value="6" selected>June</option>
                    <option value="7">July</option>
                </select>
                <button class="btn btn-primary" id="filterAttendanceBtn">Filter</button>
                <button class="btn btn-secondary" id="exportAttendanceBtn">
                    <i class="fas fa-download"></i> Export to Excel
                </button>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Day</th>
                        <th>Check In</th>
                        <th>Check Out</th>
                        <th>Working Hours</th>
                        <th>Status</th>
                        <th>Remarks</th>
                    </tr>
                </thead>
                <tbody id="detailedAttendanceTable">
                    <!-- Filled by JavaScript -->
                </tbody>
            </table>
        </div>
    </div>


    <!-- Regularization Modal -->
    <div class="modal" id="regularizationModal">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Request Regularization</h3>
                <button class="modal-close" id="closeRegularizationModal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="regularizationForm">
                    <div class="form-group">
                        <label class="form-label">Date</label>
                        <input type="date" class="form-control" id="regularizationDate" required>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Type</label>
                        <select class="form-control" id="regularizationType" required>
                            <option value="">Select Type</option>
                            <option value="forgot_checkin">Forgot Check-in</option>
                            <option value="forgot_checkout">Forgot Check-out</option>
                            <option value="late_entry">Late Entry</option>
                            <option value="early_exit">Early Exit</option>
                        </select>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label class="form-label">Actual In Time</label>
                            <input type="time" class="form-control" id="actualInTime" required>
                        </div>
                        <div class="form-group">
                            <label class="form-label">Actual Out Time</label>
                            <input type="time" class="form-control" id="actualOutTime">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Reason</label>
                        <textarea class="form-control" id="regularizationReason" rows="3" required></textarea>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Supporting Document</label>
                        <input type="file" class="form-control" id="regularizationDoc">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" id="cancelRegularizationBtn">Cancel</button>
                <button class="btn btn-success" id="submitRegularizationBtn">Submit Request</button>
            </div>
        </div>
    </div>
@endsection
